# Generated by Django 4.0.2 on 2022-02-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='token',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
